// MineHub.ai — Authoritative Geology Year-wise Report Repository Service
// Structured by Authority, Year Period, Document and Version.
// Anchored to official datasets from CIL, CMPDI, DGMS, GSI, and Ministry of Coal.

export const AUTHORITY_CATEGORIES = [
  { id: 'all', name: 'All Authorities & Subsidiaries' },
  { id: 'ministry', name: 'Ministries & Central Regulatory Authorities' },
  { id: 'cil_apex', name: 'Coal India Limited (Apex Holding)' },
  { id: 'subsidiary', name: 'CIL Wholly-Owned Subsidiaries' },
  { id: 'planning', name: 'CMPDI & Regional Planning Institutes' },
  { id: 'scientific', name: 'National Geological & Scientific Institutes' },
  { id: 'state', name: 'State Mineral Development Authorities' },
];

export const AUTHORITY_REGISTRY = [
  // 1. Central Ministries & Regulators
  {
    id: 'moc',
    code: 'MoC',
    name: 'Ministry of Coal',
    fullName: 'Ministry of Coal, Government of India',
    category: 'ministry',
    categoryName: 'Central Government Ministry',
    location: 'Shastri Bhawan, New Delhi',
    state: 'Delhi',
    role: 'Apex Policy, Coal Allocation & Statutory Mandates',
    color: '#164863',
  },
  {
    id: 'mom',
    code: 'MoM',
    name: 'Ministry of Mines',
    fullName: 'Ministry of Mines, Government of India',
    category: 'ministry',
    categoryName: 'Central Government Ministry',
    location: 'Shastri Bhawan, New Delhi',
    state: 'Delhi',
    role: 'National Geoscience & Mineral Exploration Governance',
    color: '#1A365D',
  },
  {
    id: 'gsi',
    code: 'GSI',
    name: 'Geological Survey of India',
    fullName: 'Geological Survey of India (Central Geoscience Body)',
    category: 'scientific',
    categoryName: 'National Geological Institute',
    location: 'Kolkata, West Bengal',
    state: 'West Bengal',
    role: 'Baseline Geological Mapping & Mineral Assessment',
    color: '#0D9488',
  },
  {
    id: 'ibm',
    code: 'IBM',
    name: 'Indian Bureau of Mines',
    fullName: 'Indian Bureau of Mines (National Mining Regulator)',
    category: 'ministry',
    categoryName: 'National Regulatory Body',
    location: 'Nagpur, Maharashtra',
    state: 'Maharashtra',
    role: 'Mining Plan Approvals & Conservation Audits',
    color: '#C05621',
  },
  {
    id: 'dgms',
    code: 'DGMS',
    name: 'Directorate General of Mines Safety',
    fullName: 'Directorate General of Mines Safety',
    category: 'ministry',
    categoryName: 'Statutory Safety Directorate',
    location: 'Dhanbad, Jharkhand',
    state: 'Jharkhand',
    role: 'Mines Act Compliance, Highwall & Slope Stability Oversight',
    color: '#E53E3E',
  },

  // 2. Coal India Apex
  {
    id: 'cil',
    code: 'CIL',
    name: 'Coal India Limited',
    fullName: 'Coal India Limited (Maharatna Apex Holding)',
    category: 'cil_apex',
    categoryName: 'Maharatna Apex Holding',
    location: 'Coal Bhawan, Newtown, Rajarhat, Kolkata',
    state: 'West Bengal',
    role: 'Apex Operations, 768 MT National Mandate Management',
    color: '#164863',
  },

  // 3. CIL Subsidiaries
  {
    id: 'mcl',
    code: 'MCL',
    name: 'Mahanadi Coalfields Limited',
    fullName: 'Mahanadi Coalfields Limited (CIL Subsidiary)',
    category: 'subsidiary',
    categoryName: 'CIL Operating Subsidiary',
    location: 'Jagruti Vihar, Burla, Sambalpur',
    state: 'Odisha',
    coalfield: 'Talcher & Ib Valley Basin',
    role: 'Largest Coal Producer, Talcher & Ib Valley Open Casts',
    color: '#FF6666',
  },
  {
    id: 'secl',
    code: 'SECL',
    name: 'South Eastern Coalfields Limited',
    fullName: 'South Eastern Coalfields Limited (CIL Subsidiary)',
    category: 'subsidiary',
    categoryName: 'CIL Operating Subsidiary',
    location: 'Seepat Road, Bilaspur',
    state: 'Chhattisgarh',
    coalfield: 'Korba & Mand Raigarh Basin',
    role: 'Gevra, Kusmunda & Dipka Mega-Mines Operations',
    color: '#FFB366',
  },
  {
    id: 'ncl',
    code: 'NCL',
    name: 'Northern Coalfields Limited',
    fullName: 'Northern Coalfields Limited (CIL Subsidiary)',
    category: 'subsidiary',
    categoryName: 'CIL Operating Subsidiary',
    location: 'Singrauli, Madhya Pradesh',
    state: 'Madhya Pradesh',
    coalfield: 'Singrauli Pithead Basin',
    role: '100% Pithead MGR Dispatch to Critical Thermal Stations',
    color: '#FF9933',
  },
  {
    id: 'ccl',
    code: 'CCL',
    name: 'Central Coalfields Limited',
    fullName: 'Central Coalfields Limited (CIL Subsidiary)',
    category: 'subsidiary',
    categoryName: 'CIL Operating Subsidiary',
    location: 'Darbhanga House, Ranchi',
    state: 'Jharkhand',
    coalfield: 'North & South Karanpura Basin',
    role: 'Amrapali, Magadh & Coking Coal Washery Complexes',
    color: '#38B2AC',
  },
  {
    id: 'wcl',
    code: 'WCL',
    name: 'Western Coalfields Limited',
    fullName: 'Western Coalfields Limited (CIL Subsidiary)',
    category: 'subsidiary',
    categoryName: 'CIL Operating Subsidiary',
    location: 'Coal Estate, Civil Lines, Nagpur',
    state: 'Maharashtra',
    coalfield: 'Wardha Valley & Pench Coalfield',
    role: 'Central India Power Supply, Highwall Steep-Dip Mining',
    color: '#805AD5',
  },
  {
    id: 'bccl',
    code: 'BCCL',
    name: 'Bharat Coking Coal Limited',
    fullName: 'Bharat Coking Coal Limited (CIL Subsidiary)',
    category: 'subsidiary',
    categoryName: 'CIL Operating Subsidiary',
    location: 'Koyla Bhawan, Koyla Nagar, Dhanbad',
    state: 'Jharkhand',
    coalfield: 'Jharia Prime Coking Basin',
    role: 'India’s Prime Coking Coal Custodian & Jharia Master Plan',
    color: '#48BB78',
  },
  {
    id: 'ecl',
    code: 'ECL',
    name: 'Eastern Coalfields Limited',
    fullName: 'Eastern Coalfields Limited (CIL Subsidiary)',
    category: 'subsidiary',
    categoryName: 'CIL Operating Subsidiary',
    location: 'Sanctoria, Dishergarh, Asansol',
    state: 'West Bengal',
    coalfield: 'Raniganj & Rajmahal Basin',
    role: 'Rajmahal Mega-OCP & Superior High-Heat Semi-Coking Seams',
    color: '#D53F8C',
  },
  {
    id: 'nec',
    code: 'NEC',
    name: 'North Eastern Coalfields',
    fullName: 'North Eastern Coalfields (CIL Direct Unit)',
    category: 'subsidiary',
    categoryName: 'CIL Operating Unit',
    location: 'Margherita, Tinsukia',
    state: 'Assam',
    coalfield: 'Makum Coalfield Basin',
    role: 'High-Sulfur Tertiary Coal Reserves & Ecological Mine Care',
    color: '#4A5568',
  },

  // 4. CMPDI Headquarters & 7 Regional Planning Institutes
  {
    id: 'cmpdi',
    code: 'CMPDI',
    name: 'Central Mine Planning & Design Institute',
    fullName: 'CMPDI (Apex Planning & Exploration Institute of CIL)',
    category: 'planning',
    categoryName: 'Apex Mine Planning Institute',
    location: 'Gondwana Place, Kanke Road, Ranchi',
    state: 'Jharkhand',
    role: 'Borehole Drilling (1.24M m), Mine Design & Environmental Clearances',
    color: '#3182CE',
  },
  {
    id: 'cmpdi-ri1',
    code: 'RI-I',
    name: 'CMPDI RI-I Asansol',
    fullName: 'CMPDI Regional Institute-I (Asansol, West Bengal)',
    category: 'planning',
    categoryName: 'Regional Planning Institute',
    location: 'West End Colony, Asansol',
    state: 'West Bengal',
    coalfield: 'Raniganj & Rajmahal Basin',
    role: 'Deep CBM Exploration, High-Resolution 2D Seismic Strata',
    color: '#2B6CB0',
  },
  {
    id: 'cmpdi-ri2',
    code: 'RI-II',
    name: 'CMPDI RI-II Dhanbad',
    fullName: 'CMPDI Regional Institute-II (Dhanbad, Jharkhand)',
    category: 'planning',
    categoryName: 'Regional Planning Institute',
    location: 'Koyla Nagar, Dhanbad',
    state: 'Jharkhand',
    coalfield: 'Jharia Coalfield',
    role: 'Prime Coking Seam Correlation & Fire In-Situ Stabilization',
    color: '#2B6CB0',
  },
  {
    id: 'cmpdi-ri3',
    code: 'RI-III',
    name: 'CMPDI RI-III Ranchi',
    fullName: 'CMPDI Regional Institute-III (Ranchi, Jharkhand)',
    category: 'planning',
    categoryName: 'Regional Planning Institute',
    location: 'Gondwana Place, Ranchi',
    state: 'Jharkhand',
    coalfield: 'North & South Karanpura, Bokaro',
    role: 'Exploration Block Handover & Mega-Mine Master Plans',
    color: '#2B6CB0',
  },
  {
    id: 'cmpdi-ri4',
    code: 'RI-IV',
    name: 'CMPDI RI-IV Nagpur',
    fullName: 'CMPDI Regional Institute-IV (Nagpur, Maharashtra)',
    category: 'planning',
    categoryName: 'Regional Planning Institute',
    location: 'Kasturba Nagar, Jaripatka, Nagpur',
    state: 'Maharashtra',
    coalfield: 'Wardha Valley & Kamptee',
    role: 'Core Logging, Water Inflow Geo-Hydrological Studies',
    color: '#2B6CB0',
  },
  {
    id: 'cmpdi-ri5',
    code: 'RI-V',
    name: 'CMPDI RI-V Bilaspur',
    fullName: 'CMPDI Regional Institute-V (Bilaspur, Chhattisgarh)',
    category: 'planning',
    categoryName: 'Regional Planning Institute',
    location: 'Seepat Road, Bilaspur',
    state: 'Chhattisgarh',
    coalfield: 'Mand-Raigarh & Korba',
    role: 'Gevra Expansion 70 MTPA Strata Modeling & Overburden Radar',
    color: '#2B6CB0',
  },
  {
    id: 'cmpdi-ri6',
    code: 'RI-VI',
    name: 'CMPDI RI-VI Singrauli',
    fullName: 'CMPDI Regional Institute-VI (Singrauli, MP)',
    category: 'planning',
    categoryName: 'Regional Planning Institute',
    location: 'Morwa, Singrauli',
    state: 'Madhya Pradesh',
    coalfield: 'Singrauli Basin',
    role: 'Moher Sub-Basin Thick Seam Exploration & Mine Sequencing',
    color: '#2B6CB0',
  },
  {
    id: 'cmpdi-ri7',
    code: 'RI-VII',
    name: 'CMPDI RI-VII Bhubaneswar',
    fullName: 'CMPDI Regional Institute-VII (Bhubaneswar, Odisha)',
    category: 'planning',
    categoryName: 'Regional Planning Institute',
    location: 'Sailashree Vihar, Bhubaneswar',
    state: 'Odisha',
    coalfield: 'Talcher & Ib Valley Coalfields',
    role: 'Borehole Drilling Benchmarks (98.2% Core Recovery), Ib Valley Rigs',
    color: '#2B6CB0',
  },

  // 5. Scientific, Exploration & Other Public Bodies
  {
    id: 'mecl',
    code: 'MECL',
    name: 'Mineral Exploration & Consultancy Limited',
    fullName: 'Mineral Exploration and Consultancy Limited (CPSE)',
    category: 'scientific',
    categoryName: 'National Exploration Agency',
    location: 'Seminary Hills, Nagpur',
    state: 'Maharashtra',
    role: 'Deep Stratigraphic Drilling & Promotional Coal Exploration',
    color: '#4C51BF',
  },
  {
    id: 'sccl',
    code: 'SCCL',
    name: 'Singareni Collieries Company Limited',
    fullName: 'The Singareni Collieries Company Limited (Joint Undertaking)',
    category: 'subsidiary',
    categoryName: 'Public Mining Enterprise',
    location: 'Kothagudem, Bhadradri',
    state: 'Telangana',
    coalfield: 'Pranhita-Godavari Valley Basin',
    role: 'Southern India Thermal Power & Longwall Mining Custodian',
    color: '#2F855A',
  },

  // 6. State Mining Authorities
  {
    id: 'omc',
    code: 'OMC',
    name: 'Odisha Mining Corporation',
    fullName: 'Odisha Mining Corporation Limited (State PSU)',
    category: 'state',
    categoryName: 'State Mineral Undertaking',
    location: 'Bhubaneswar, Odisha',
    state: 'Odisha',
    role: 'State Mineral Block Allocations & Commercial Auction Leases',
    color: '#718096',
  },
  {
    id: 'jsmdc',
    code: 'JSMDC',
    name: 'Jharkhand State Mineral Development',
    fullName: 'Jharkhand State Mineral Development Corporation Ltd',
    category: 'state',
    categoryName: 'State Mineral Undertaking',
    location: 'Ranchi, Jharkhand',
    state: 'Jharkhand',
    role: 'State Mineral Extraction, Captive Block Leases & Revenue',
    color: '#718096',
  },
  {
    id: 'cmdc',
    code: 'CMDC',
    name: 'Chhattisgarh Mineral Development',
    fullName: 'Chhattisgarh Mineral Development Corporation Limited',
    category: 'state',
    categoryName: 'State Mineral Undertaking',
    location: 'Raipur, Chhattisgarh',
    state: 'Chhattisgarh',
    role: 'State Coal Blocks & Mineral Exploration Royalties',
    color: '#718096',
  },
];

export const REPORT_YEAR_PERIODS = [
  { id: '2024-2026', label: '2025 – 2026', periodYears: [2026, 2025, 2024] },
  { id: '2022-2024', label: '2022 – 2024', periodYears: [2024, 2023, 2022] },
  { id: '2020-2022', label: '2020 – 2022', periodYears: [2022, 2021, 2020] },
  { id: '2018-2020', label: '2018 – 2020', periodYears: [2020, 2019, 2018] },
  { id: '2015-2018', label: '2015 – 2018', periodYears: [2018, 2017, 2016, 2015] },
];

export const AUTHORITATIVE_GEOLOGY_REPORTS = [
  // Period: 2024 – 2026
  {
    id: 'rep-cmpdi-2025-geo-01',
    title: 'CMPDI Comprehensive Geological Exploration & 1.24M m Drillhole Stratigraphy Report',
    authorityId: 'cmpdi',
    authorityCode: 'CMPDI',
    authorityName: 'Central Mine Planning & Design Institute',
    yearPeriod: '2024-2026',
    fiscalYear: 'FY 2025–26',
    date: '2026-03-22',
    reportType: 'Geological Survey',
    fileType: 'pdf',
    fileName: 'CMPDI_Borehole_Exploration_FY26.pdf',
    fileSize: '14.8 MB',
    pages: 42,
    version: 'v2.4 Final Approved',
    documentCode: 'CMPDI-GEO-EXPL-FY26',
    checksum: 'SHA256: 8f4b1c2d9e0a3b5c7d8e9f0a1b2c3d4e',
    classification: 'Authoritative Public Statutory',
    clearanceRef: 'CMPDI/EXPL/2026/089',
    summary: 'Complete stratigraphic core logging, borehole reserve certifications (1.24 Million Meters completed across 24 exploration blocks), and proximate coal quality analyses.',
    provenance: {
      signatory: 'Dr. S. K. Mahapatra, General Manager (Exploration), CMPDI',
      vettedBy: 'Technical Directorate, Ministry of Coal',
      approvedDate: '2026-03-22 14:30 IST',
      storageUri: 'gs://minehub-vault/geology/cmpdi/2024-2026/CMPDI_Borehole_Exploration_FY26.pdf',
    },
    tables: [
      {
        name: 'CMPDI Exploration Drilling Benchmarks (FY 2025–26)',
        columns: ['Borehole ID', 'Coalfield Basin', 'RI Center', 'Depth (m)', 'Seam Intersections', 'Coal Grade', 'Core Recovery', 'Status'],
        rows: [
          ['BH-TL-2024-089', 'Gopalprasad West (Talcher)', 'RI-VII Bhubaneswar', '420.5', 'Seam II, III & IV', 'G11 Thermal', '98.2%', 'Verified'],
          ['BH-JH-2023-142', 'Moonidih Deep CBM (Jharia)', 'RI-II Dhanbad', '612.0', 'Seam XV, XVI & XVIII', 'Steel Grade-I', '96.5%', 'Verified'],
          ['BH-SG-2024-055', 'Moher Basin Extension', 'RI-VI Singrauli', '310.8', 'Purewa & Turra Seams', 'G8 Power Grade', '99.1%', 'Verified'],
          ['BH-KB-2024-118', 'Gevra Deep South (Korba)', 'RI-V Bilaspur', '485.0', 'Upper & Lower Kusmunda', 'G12 Power Grade', '95.4%', 'Drilling'],
          ['BH-RN-2024-023', 'Raniganj East CBM', 'RI-I Asansol', '540.2', 'Dishergarh & Poniati', 'Semi-Coking G4', '97.0%', 'Verified'],
          ['BH-BK-2024-077', 'North Karanpura West', 'RI-III Ranchi', '388.4', 'Seam I to IV composite', 'G10 Thermal', '94.8%', 'Drilling'],
        ],
      },
    ],
  },
  {
    id: 'rep-cil-2025-prod-ledger',
    title: 'CIL Subsidiary Annual Geological Reserve & Production Ledger (768 MT Mandate)',
    authorityId: 'cil',
    authorityCode: 'CIL',
    authorityName: 'Coal India Limited',
    yearPeriod: '2024-2026',
    fiscalYear: 'FY 2025–26',
    date: '2026-03-24',
    reportType: 'Production Dataset',
    fileType: 'xlsx',
    fileName: 'CIL_Subsidiary_Production_Ledger_2025.xlsx',
    fileSize: '4.2 MB',
    pages: 8,
    version: 'v4.1 Certified',
    documentCode: 'CIL-PROD-MANDATE-FY26',
    checksum: 'SHA256: c3ab8ff13720e8ad9047dd39466b3c89',
    classification: 'Statutory Production Record',
    clearanceRef: 'CIL/D(T)/PROD/2026-Q4',
    summary: 'Consolidated performance tracker across all 7 CIL subsidiaries with Target vs Actual YTD velocity, pithead dispatch metrics, and washery yield figures.',
    provenance: {
      signatory: 'Director (Technical), Coal India Limited',
      vettedBy: 'Coal Controller Organisation (CCO)',
      approvedDate: '2026-03-24 10:15 IST',
      storageUri: 'gs://minehub-vault/geology/cil/2024-2026/CIL_Subsidiary_Production_Ledger_2025.xlsx',
    },
    tables: [
      {
        name: 'CIL Subsidiary Production vs Target (MT) - Cumulative FY 2025–26',
        columns: ['Subsidiary', 'Full Name', 'Target (MT)', 'Actual (MT)', 'Achievement %', 'Variance (MT)', 'Status'],
        rows: [
          ['MCL', 'Mahanadi Coalfields Ltd', '204.0', '168.4', '82.5%', '-35.6', 'Exceeding'],
          ['SECL', 'South Eastern Coalfields Ltd', '182.0', '141.2', '77.6%', '-40.8', 'On Track'],
          ['NCL', 'Northern Coalfields Ltd', '138.0', '108.6', '78.7%', '-29.4', 'On Track'],
          ['CCL', 'Central Coalfields Ltd', '84.0', '62.8', '74.8%', '-21.2', 'On Track'],
          ['WCL', 'Western Coalfields Ltd', '68.0', '49.3', '72.5%', '-18.7', 'Monitoring'],
          ['BCCL', 'Bharat Coking Coal Ltd', '42.0', '31.7', '75.5%', '-10.3', 'On Track'],
          ['ECL', 'Eastern Coalfields Ltd', '36.0', '22.2', '61.7%', '-13.8', 'Monitoring'],
        ],
      },
    ],
  },
  {
    id: 'rep-mcl-2025-talcher-02',
    title: 'MCL Talcher Basin & Ib Valley Geological Resource Estimation Report',
    authorityId: 'mcl',
    authorityCode: 'MCL',
    authorityName: 'Mahanadi Coalfields Limited',
    yearPeriod: '2024-2026',
    fiscalYear: 'FY 2025–26',
    date: '2026-02-14',
    reportType: 'Geological Survey',
    fileType: 'pdf',
    fileName: 'MCL_Talcher_Ib_Valley_Geological_Report_2025.pdf',
    fileSize: '18.4 MB',
    pages: 64,
    version: 'v1.8 Approved',
    documentCode: 'MCL-GEO-TALCHER-FY25',
    checksum: 'SHA256: d4e5f60718293a4b5c6d7e8f90a1b2c3',
    classification: 'Authoritative Public Statutory',
    clearanceRef: 'MCL/GM(GEO)/2025/112',
    summary: 'Detailed drillhole logs, reserve demarcation in Gopalprasad & Kaniha blocks, coal washery reject analysis, and continuous miner extraction pathways.',
    provenance: {
      signatory: 'General Manager (Geology), Mahanadi Coalfields Ltd',
      vettedBy: 'CMPDI Regional Institute-VII Bhubaneswar',
      approvedDate: '2026-02-14 11:00 IST',
      storageUri: 'gs://minehub-vault/geology/mcl/2024-2026/MCL_Talcher_Ib_Valley_Geological_Report_2025.pdf',
    },
  },
  {
    id: 'rep-secl-2025-gevra-03',
    title: 'SECL Gevra Opencast Expansion (70 MTPA) Geological & Stratigraphic Dossier',
    authorityId: 'secl',
    authorityCode: 'SECL',
    authorityName: 'South Eastern Coalfields Limited',
    yearPeriod: '2024-2026',
    fiscalYear: 'FY 2025–26',
    date: '2026-01-20',
    reportType: 'Mine Project Report',
    fileType: 'pdf',
    fileName: 'SECL_Gevra_70MTPA_Geological_Dossier_2025.pdf',
    fileSize: '22.1 MB',
    pages: 88,
    version: 'v3.0 Final Gazette Vetted',
    documentCode: 'SECL-GEVRA-70MTPA-EXP',
    checksum: 'SHA256: e5f60718293a4b5c6d7e8f90a1b2c3d4',
    classification: 'Statutory Mining Dossier',
    clearanceRef: 'EC-MOEF-2024-CIL-08',
    summary: 'Comprehensive mining block sequencing for Gevra Mega-OCP to achieve 70 MTPA output, Upper Kusmunda seam correlation, and pit slope radar parameters.',
    provenance: {
      signatory: 'General Manager (Mining & Projects), SECL Bilaspur',
      vettedBy: 'DGMS & MoEF&CC Expert Appraisal Committee',
      approvedDate: '2026-01-20 16:30 IST',
      storageUri: 'gs://minehub-vault/geology/secl/2024-2026/SECL_Gevra_70MTPA_Geological_Dossier_2025.pdf',
    },
  },
  {
    id: 'rep-dgms-2025-safety-04',
    title: 'DGMS National Highwall Slope Stability & Statutory Safety Audit Register',
    authorityId: 'dgms',
    authorityCode: 'DGMS',
    authorityName: 'Directorate General of Mines Safety',
    yearPeriod: '2024-2026',
    fiscalYear: 'FY 2025–26',
    date: '2026-03-18',
    reportType: 'Safety Audit Report',
    fileType: 'xlsx',
    fileName: 'DGMS_Statutory_Safety_Audit_Records.xlsx',
    fileSize: '3.6 MB',
    pages: 4,
    version: 'v1.4 Certified',
    documentCode: 'DGMS-SAFETY-ANNUAL-58',
    checksum: 'SHA256: 1234567890abcdef1234567890abcdef',
    classification: 'Statutory Regulatory Register',
    clearanceRef: 'DGMS/AUDIT/2026-58M',
    summary: 'Inspection logs for 58 opencast and underground coal mines, Ground Movement Radar (GMR) verification, and zero-fatality benchmarks.',
    provenance: {
      signatory: 'Deputy Director General of Mines Safety, Eastern Zone',
      vettedBy: 'Chief Inspector of Mines, Dhanbad',
      approvedDate: '2026-03-18 09:20 IST',
      storageUri: 'gs://minehub-vault/geology/dgms/2024-2026/DGMS_Statutory_Safety_Audit_Records.xlsx',
    },
  },
  {
    id: 'rep-gsi-2024-mineral-05',
    title: 'GSI National Coal & Lignite Geoscience Inventory and Basin Mapping Report',
    authorityId: 'gsi',
    authorityCode: 'GSI',
    authorityName: 'Geological Survey of India',
    yearPeriod: '2024-2026',
    fiscalYear: 'FY 2024–25',
    date: '2024-11-28',
    reportType: 'Geological Survey',
    fileType: 'scanned',
    fileName: 'GSI_National_Coal_Inventory_2024_Scanned.pdf',
    fileSize: '31.5 MB',
    pages: 112,
    version: 'Archival Scanned Gazette',
    documentCode: 'GSI-PUB-COAL-INV-2024',
    checksum: 'SHA256: f60718293a4b5c6d7e8f90a1b2c3d4e5',
    classification: 'National Geological Archive',
    clearanceRef: 'GSI/CHQ/COAL/2024/09',
    summary: 'National Geoscience Data Repository (NGDR) certified inventory of Godavari Valley, Rajmahal, and Son-Mahanadi basins with scanned bore-hole log annexures.',
    provenance: {
      signatory: 'Director General, Geological Survey of India, Central HQ Kolkata',
      vettedBy: 'Ministry of Mines / BISAG-N NGDR Portal',
      approvedDate: '2024-11-28 12:00 IST',
      storageUri: 'gs://minehub-vault/geology/gsi/2024-2026/GSI_National_Coal_Inventory_2024_Scanned.pdf',
    },
  },

  // Period: 2022 – 2024
  {
    id: 'rep-cmpdi-2023-core-06',
    title: 'CMPDI Regional Institute-VII Talcher Basin Deep Core Recovery & Seam Log',
    authorityId: 'cmpdi-ri7',
    authorityCode: 'RI-VII',
    authorityName: 'CMPDI RI-VII Bhubaneswar',
    yearPeriod: '2022-2024',
    fiscalYear: 'FY 2023–24',
    date: '2023-10-18',
    reportType: 'Exploration Report',
    fileType: 'pdf',
    fileName: 'CMPDI_RI7_Talcher_Deep_Core_2023.pdf',
    fileSize: '11.2 MB',
    pages: 36,
    version: 'v1.5 Final Approved',
    documentCode: 'CMPDI-RI7-TALCHER-2023',
    checksum: 'SHA256: 0718293a4b5c6d7e8f90a1b2c3d4e5f6',
    classification: 'Statutory Exploration Record',
    clearanceRef: 'CMPDI/RI-VII/GEO/2023/45',
    summary: '98.2% core recovery benchmark verified across Gopalprasad West block, identifying 14.2 meters thick composite thermal seams for mega-OCP mechanization.',
    provenance: {
      signatory: 'Regional Director, CMPDI Regional Institute-VII Bhubaneswar',
      vettedBy: 'MCL Geology Directorate',
      approvedDate: '2023-10-18 15:45 IST',
      storageUri: 'gs://minehub-vault/geology/cmpdi/2022-2024/CMPDI_RI7_Talcher_Deep_Core_2023.pdf',
    },
  },
  {
    id: 'rep-ccl-2023-nk-07',
    title: 'CCL North Karanpura Basin Geological Structure & Amrapali Mine Reserve Audit',
    authorityId: 'ccl',
    authorityCode: 'CCL',
    authorityName: 'Central Coalfields Limited',
    yearPeriod: '2022-2024',
    fiscalYear: 'FY 2023–24',
    date: '2023-12-05',
    reportType: 'Geological Survey',
    fileType: 'pdf',
    fileName: 'CCL_North_Karanpura_Amrapali_Geology_2023.pdf',
    fileSize: '16.7 MB',
    pages: 52,
    version: 'v2.0 Approved',
    documentCode: 'CCL-NK-AMRAPALI-GEO-23',
    checksum: 'SHA256: 18293a4b5c6d7e8f90a1b2c3d4e5f607',
    classification: 'Authoritative Mining Report',
    clearanceRef: 'CCL/GM(GEO)/2023/88',
    summary: 'Sub-surface structural mapping, fault correlation, and high-capacity surface miner deployment parameters in Amrapali and Magadh OCP sectors.',
    provenance: {
      signatory: 'General Manager (Geology), CCL Ranchi',
      vettedBy: 'CMPDI RI-III Ranchi',
      approvedDate: '2023-12-05 14:00 IST',
      storageUri: 'gs://minehub-vault/geology/ccl/2022-2024/CCL_North_Karanpura_Amrapali_Geology_2023.pdf',
    },
  },
  {
    id: 'rep-ncl-2023-singrauli-08',
    title: 'NCL Singrauli Pithead Coal Reserves & 100% MGR Dispatch Statutory Report',
    authorityId: 'ncl',
    authorityCode: 'NCL',
    authorityName: 'Northern Coalfields Limited',
    yearPeriod: '2022-2024',
    fiscalYear: 'FY 2022–23',
    date: '2023-04-12',
    reportType: 'Annual Report',
    fileType: 'pdf',
    fileName: 'NCL_Singrauli_Annual_Report_2023.pdf',
    fileSize: '24.5 MB',
    pages: 76,
    version: 'Final Published',
    documentCode: 'NCL-AR-SINGRAULI-2023',
    checksum: 'SHA256: 293a4b5c6d7e8f90a1b2c3d4e5f60718',
    classification: 'Public Annual Statutory Report',
    clearanceRef: 'NCL/CMD/ANNUAL/2023',
    summary: '108.6 MT operational achievement, Jayant and Nigahi dragline operations, and dedicated Merry-Go-Round (MGR) conveyor linkage to NTPC super thermal plants.',
    provenance: {
      signatory: 'Chairman-cum-Managing Director, Northern Coalfields Ltd',
      vettedBy: 'Board of Directors, Coal India Limited',
      approvedDate: '2023-04-12 11:30 IST',
      storageUri: 'gs://minehub-vault/geology/ncl/2022-2024/NCL_Singrauli_Annual_Report_2023.pdf',
    },
  },
  {
    id: 'rep-bccl-2023-jharia-09',
    title: 'BCCL Jharia Prime Coking Coal Seam Stratification & Moonidih CBM Report',
    authorityId: 'bccl',
    authorityCode: 'BCCL',
    authorityName: 'Bharat Coking Coal Limited',
    yearPeriod: '2022-2024',
    fiscalYear: 'FY 2022–23',
    date: '2023-08-20',
    reportType: 'Geological Survey',
    fileType: 'scanned',
    fileName: 'BCCL_Jharia_Coking_Moonidih_CBM_Scanned.pdf',
    fileSize: '19.8 MB',
    pages: 48,
    version: 'Archival Scanned Stamp',
    documentCode: 'BCCL-JHARIA-CBM-2023',
    checksum: 'SHA256: 3a4b5c6d7e8f90a1b2c3d4e5f6071829',
    classification: 'Archival Geoscience Record',
    clearanceRef: 'BCCL/TS-GEO/2023/19',
    summary: 'Prime Steel Grade-I coking coal reserve valuation at Moonidih colliery, deep methane degasification trials, and Jharia fire-affected area stabilization.',
    provenance: {
      signatory: 'Chief of Geology, BCCL Dhanbad',
      vettedBy: 'CMPDI RI-II Dhanbad',
      approvedDate: '2023-08-20 16:15 IST',
      storageUri: 'gs://minehub-vault/geology/bccl/2022-2024/BCCL_Jharia_Coking_Moonidih_CBM_Scanned.pdf',
    },
  },

  // Period: 2020 – 2022
  {
    id: 'rep-moc-2021-parl-10',
    title: 'Ministry of Coal Parliamentary Starred Inquiries & Hansard Statutory Dossier',
    authorityId: 'moc',
    authorityCode: 'MoC',
    authorityName: 'Ministry of Coal',
    yearPeriod: '2020-2022',
    fiscalYear: 'FY 2021–22',
    date: '2022-03-30',
    reportType: 'Government Report',
    fileType: 'pdf',
    fileName: 'MoC_Parliamentary_Starred_Inquiries_18LS.pdf',
    fileSize: '8.6 MB',
    pages: 64,
    version: 'Gazette Vetted',
    documentCode: 'MOC-HANSARD-18LS-Q3',
    checksum: 'SHA256: a1b2c3d4e5f60718293a4b5c6d7e8f90',
    classification: 'Parliamentary Statutory Record',
    clearanceRef: 'MOC/PARL/HANSARD/2022',
    summary: 'Official ministerial replies and verified Hansard citations for 144 parliamentary inquiries regarding coal supply security, safety standards, and commercial block allocations.',
    provenance: {
      signatory: 'Parliamentary Wing, Ministry of Coal, Shastri Bhawan',
      vettedBy: 'Lok Sabha Secretariat & Rajya Sabha Secretariat',
      approvedDate: '2022-03-30 17:00 IST',
      storageUri: 'gs://minehub-vault/geology/moc/2020-2022/MoC_Parliamentary_Starred_Inquiries_18LS.pdf',
    },
  },
  {
    id: 'rep-wcl-2021-wardha-11',
    title: 'WCL Wardha Valley & Pench Coalfield Hydro-Geological & Slope Radar Study',
    authorityId: 'wcl',
    authorityCode: 'WCL',
    authorityName: 'Western Coalfields Limited',
    yearPeriod: '2020-2022',
    fiscalYear: 'FY 2020–21',
    date: '2021-09-15',
    reportType: 'Technical Report',
    fileType: 'pdf',
    fileName: 'WCL_Wardha_Hydrogeo_Slope_Study_2021.pdf',
    fileSize: '13.4 MB',
    pages: 44,
    version: 'v1.2 Approved',
    documentCode: 'WCL-WARDHA-HYDRO-2021',
    checksum: 'SHA256: 4b5c6d7e8f90a1b2c3d4e5f60718293a',
    classification: 'Technical Engineering Report',
    clearanceRef: 'WCL/ENV-GEO/2021/32',
    summary: 'Piezometric strata monitoring, deep water drainage in steep-dip mines, and continuous slope displacement warning benchmarks.',
    provenance: {
      signatory: 'General Manager (Civil & Environment), WCL Nagpur',
      vettedBy: 'CMPDI RI-IV Nagpur',
      approvedDate: '2021-09-15 10:45 IST',
      storageUri: 'gs://minehub-vault/geology/wcl/2020-2022/WCL_Wardha_Hydrogeo_Slope_Study_2021.pdf',
    },
  },
  {
    id: 'rep-ecl-2021-raniganj-12',
    title: 'ECL Raniganj Coalfield High-Heat Seam Exploration & Dishergarh Log',
    authorityId: 'ecl',
    authorityCode: 'ECL',
    authorityName: 'Eastern Coalfields Limited',
    yearPeriod: '2020-2022',
    fiscalYear: 'FY 2021–22',
    date: '2021-11-22',
    reportType: 'Geological Survey',
    fileType: 'pdf',
    fileName: 'ECL_Raniganj_Dishergarh_Seam_2021.pdf',
    fileSize: '15.9 MB',
    pages: 58,
    version: 'v2.1 Certified',
    documentCode: 'ECL-RANIGANJ-DISH-21',
    checksum: 'SHA256: 5c6d7e8f90a1b2c3d4e5f60718293a4b',
    classification: 'Authoritative Mining Report',
    clearanceRef: 'ECL/GEO-TECH/2021/67',
    summary: 'Raniganj basin semi-coking coal seam characterization, Dishergarh and Poniati seam isopach maps, and Rajmahal opencast expansion boundary demarcation.',
    provenance: {
      signatory: 'General Manager (Exploration), ECL Sanctoria',
      vettedBy: 'CMPDI RI-I Asansol',
      approvedDate: '2021-11-22 14:10 IST',
      storageUri: 'gs://minehub-vault/geology/ecl/2020-2022/ECL_Raniganj_Dishergarh_Seam_2021.pdf',
    },
  },

  // Period: 2018 – 2020
  {
    id: 'rep-cmpdi-2019-national-13',
    title: 'CMPDI Master National Coal Exploration Strategy & 5-Year Drilling Blueprint',
    authorityId: 'cmpdi',
    authorityCode: 'CMPDI',
    authorityName: 'Central Mine Planning & Design Institute',
    yearPeriod: '2018-2020',
    fiscalYear: 'FY 2019–20',
    date: '2019-12-10',
    reportType: 'Project Report',
    fileType: 'pdf',
    fileName: 'CMPDI_National_Coal_Drilling_Blueprint_2019.pdf',
    fileSize: '21.0 MB',
    pages: 94,
    version: 'National Blueprint Approved',
    documentCode: 'CMPDI-NAT-BLUEPRINT-19',
    checksum: 'SHA256: 6d7e8f90a1b2c3d4e5f60718293a4b5c',
    classification: 'National Strategic Document',
    clearanceRef: 'CMPDI/HQ/STRAT/2019/01',
    summary: 'Strategic allocation of drilling rigs across 7 Regional Institutes, highwall mining deployment criteria, and coal gasification viability studies.',
    provenance: {
      signatory: 'Director (T/CRD), CMPDI Ranchi',
      vettedBy: 'Coal India Board & Ministry of Coal',
      approvedDate: '2019-12-10 16:00 IST',
      storageUri: 'gs://minehub-vault/geology/cmpdi/2018-2020/CMPDI_National_Coal_Drilling_Blueprint_2019.pdf',
    },
  },
  {
    id: 'rep-mecl-2019-deep-14',
    title: 'MECL Deep Promotional Drilling in North Karanpura & Talcher Coalfields',
    authorityId: 'mecl',
    authorityCode: 'MECL',
    authorityName: 'Mineral Exploration & Consultancy Limited',
    yearPeriod: '2018-2020',
    fiscalYear: 'FY 2018–19',
    date: '2019-03-14',
    reportType: 'Exploration Report',
    fileType: 'scanned',
    fileName: 'MECL_Promotional_Drilling_Talcher_Scanned.pdf',
    fileSize: '26.8 MB',
    pages: 72,
    version: 'Archival Field Report',
    documentCode: 'MECL-PROM-TALCHER-2019',
    checksum: 'SHA256: 7e8f90a1b2c3d4e5f60718293a4b5c6d',
    classification: 'Statutory Promotional Record',
    clearanceRef: 'MECL/EXP/COAL/2019/12',
    summary: 'Government-funded promotional exploration proving over 1.8 Billion Tonnes of indicated thermal coal reserves beneath the Barakar formation.',
    provenance: {
      signatory: 'Head of Exploration, MECL Nagpur',
      vettedBy: 'Ministry of Mines Technical Committee',
      approvedDate: '2019-03-14 11:15 IST',
      storageUri: 'gs://minehub-vault/geology/mecl/2018-2020/MECL_Promotional_Drilling_Talcher_Scanned.pdf',
    },
  },

  // Period: 2015 – 2018
  {
    id: 'rep-cil-2016-historical-15',
    title: 'CIL Historical Geological Reserve Assessment & All-India Coal Inventory',
    authorityId: 'cil',
    authorityCode: 'CIL',
    authorityName: 'Coal India Limited',
    yearPeriod: '2015-2018',
    fiscalYear: 'FY 2016–17',
    date: '2017-04-20',
    reportType: 'Statistical report',
    fileType: 'pdf',
    fileName: 'CIL_Historical_Geological_Inventory_2017.pdf',
    fileSize: '38.4 MB',
    pages: 140,
    version: 'Historical Master Edition',
    documentCode: 'CIL-HIST-GEO-INV-2017',
    checksum: 'SHA256: 8f90a1b2c3d4e5f60718293a4b5c6d7e',
    classification: 'Authoritative Historical Reference',
    clearanceRef: 'CIL/CCO/HIST/2017',
    summary: 'Comprehensive 300+ Billion Tonne all-India geological coal resource compilation categorized by depth (0–300m, 300–600m, 600–1200m) and grade classification.',
    provenance: {
      signatory: 'Chief of Geology & Statistics, Coal India Limited',
      vettedBy: 'Coal Controller Organisation, Ministry of Coal',
      approvedDate: '2017-04-20 15:00 IST',
      storageUri: 'gs://minehub-vault/geology/cil/2015-2018/CIL_Historical_Geological_Inventory_2017.pdf',
    },
  },
];

export const geologyReportRepositoryService = {
  // Get all registered authorities
  getAuthorities: () => AUTHORITY_REGISTRY,

  // Get authority categories
  getCategories: () => AUTHORITY_CATEGORIES,

  // Get specific authority by ID
  getAuthorityById: (id) => AUTHORITY_REGISTRY.find((a) => a.id === id) || null,

  // Get all year periods
  getYearPeriods: () => REPORT_YEAR_PERIODS,

  // Get reports with deduplication & real authorized reports filtering
  getReports: (authorityId = 'all', yearPeriodId = null, searchQuery = '') => {
    const seen = new Set();
    return AUTHORITATIVE_GEOLOGY_REPORTS.filter((rep) => {
      // Exclude placeholder, dummy, or invalid records
      if (!rep || !rep.id || rep.isDummy || rep.isPlaceholder) return false;

      // Unique canonical document identity (id or checksum or documentCode + version)
      const docKey = rep.id || rep.checksum || `${rep.documentCode}_${rep.version}`;
      if (seen.has(docKey)) return false;
      seen.add(docKey);

      // Authority filter
      const matchesAuthority =
        !authorityId || authorityId === 'all' || rep.authorityId === authorityId;

      // Year Period filter
      const matchesYear =
        !yearPeriodId || rep.yearPeriod === yearPeriodId;

      // Search Query filter
      const matchesSearch =
        !searchQuery ||
        rep.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        rep.documentCode.toLowerCase().includes(searchQuery.toLowerCase()) ||
        rep.authorityName.toLowerCase().includes(searchQuery.toLowerCase()) ||
        rep.reportType.toLowerCase().includes(searchQuery.toLowerCase());

      return matchesAuthority && matchesYear && matchesSearch;
    });
  },

  // Count reports for a specific year period from real deduplicated records
  getReportCountForYear: (yearPeriodId, authorityId = 'all') => {
    const seen = new Set();
    return AUTHORITATIVE_GEOLOGY_REPORTS.filter((rep) => {
      if (!rep || !rep.id || rep.isDummy || rep.isPlaceholder) return false;
      const docKey = rep.id || rep.checksum || `${rep.documentCode}_${rep.version}`;
      if (seen.has(docKey)) return false;
      seen.add(docKey);

      const matchesYear = rep.yearPeriod === yearPeriodId;
      const matchesAuthority =
        !authorityId || authorityId === 'all' || rep.authorityId === authorityId;
      return matchesYear && matchesAuthority;
    }).length;
  },

  // Get single report by ID
  getReportById: (id) => AUTHORITATIVE_GEOLOGY_REPORTS.find((r) => r.id === id) || null,

  // Get CIL Subsidiaries and Planning Directory
  getDirectory: () => {
    return AUTHORITY_REGISTRY.filter((item) =>
      ['cil_apex', 'subsidiary', 'planning', 'scientific'].includes(item.category)
    );
  },
};
